#!/usr/bin/env python3
"""
r_codegen.py  —  JSON → mrgsolve R Simulation Generator
=========================================================
Takes a pk_pipeline JSON output and produces:
  1. A mrgsolve .cpp model file
  2. An R simulation script that runs it
  3. Executes R via subprocess to produce a concentration-time CSV + plot
"""

import argparse
import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_sym(sym: Optional[str], name: str) -> str:
    """Return a clean C-identifier symbol, derived from sym or name."""
    raw = sym if sym else name
    # Keep only alphanumeric + underscore, collapse spaces/hyphens
    clean = re.sub(r"[^A-Za-z0-9_]", "_", raw).strip("_")
    # Collapse multiple underscores
    clean = re.sub(r"_+", "_", clean)
    return clean[:40] or "param"


def _extract_compound_groups(params: List[Dict]) -> Dict[str, List[Dict]]:
    """Group parameters by compound (None → 'Physiological')."""
    groups: Dict[str, list] = defaultdict(list)
    for p in params:
        c = (p.get("context") or {}).get("compound") or "Physiological"
        groups[c].append(p)
    return dict(groups)


def _best_value(p: Dict) -> Optional[float]:
    qd = p.get("quantitative_data") or {}
    return qd.get("value")


def _pick_species(params: List[Dict]) -> str:
    for p in params:
        sp = (p.get("context") or {}).get("subject_species")
        if sp:
            return sp
    return "Unknown"


# ---------------------------------------------------------------------------
# mrgsolve .cpp generator
# ---------------------------------------------------------------------------

CPP_TEMPLATE = """\
// ============================================================
//  mrgsolve model: {title}
//  Generated by r_codegen.py from pk_pipeline JSON output
//  Species: {species}
//  Compounds: {compounds}
// ============================================================

$PROB
{title}
Source: pk_pipeline auto-generated model

$PARAM
// ---- Physiological parameters ----
{phys_params}

// ---- Compound-specific parameters ({main_compound}) ----
{cmpd_params}

$CMT
// Compartments extracted from model structure diagram
{compartments}

$GLOBAL
// Derived quantities
{global_block}

$ODE
// Differential equations
{ode_block}

$TABLE
{table_block}
"""


def _build_param_block(params: List[Dict]) -> Tuple[str, List[str]]:
    """Return (formatted param block, list of symbol names)."""
    lines = []
    symbols = []
    seen = set()
    for p in params:
        sym = _safe_sym(p.get("symbol"), p.get("parameter_name", "p"))
        val = _best_value(p)
        if val is None:
            val = 0.0  # placeholder
        if sym in seen:
            sym = sym + "_2"
        seen.add(sym)
        symbols.append(sym)
        unit = (p.get("quantitative_data") or {}).get("unit") or ""
        name = p.get("parameter_name", "")
        comment = f" // {name}" + (f" [{unit}]" if unit else "")
        lines.append(f"{sym} = {val},{comment}")
    return "\n".join(lines), symbols


def _build_compartments(structure: Optional[Dict]) -> Tuple[str, List[str]]:
    """Return (CMT block string, list of compartment ids)."""
    if not structure or not structure.get("compartments"):
        return "CENTRAL  // fallback single compartment", ["CENTRAL"]

    cmts = []
    for c in structure["compartments"]:
        cid = _safe_sym(c.get("id"), c.get("label_raw", "cmt")).upper()
        label = c.get("label_raw", "")
        cmts.append(f"{cid}  // {label}")
    return "\n".join(cmts), [c.split()[0] for c in cmts]


def _build_ode(structure: Optional[Dict], cmt_ids: List[str]) -> str:
    """Build ODE block from compartment connections."""
    if not structure or not structure.get("connections"):
        return "// TODO: Add ODE equations manually\ndADT(1) = -CL * CENTRAL / VC;"

    lines = ["// Auto-generated from model structure diagram"]
    lines.append("// Review and adjust rate expressions as needed")
    lines.append("")

    seen_cmts = {c: 0 for c in cmt_ids}  # track if cmt appears in ODE

    for conn in structure.get("connections", []):
        src = conn.get("source", "").upper()
        tgt = conn.get("target", "").upper()
        label = conn.get("label_raw", "k")
        direction = conn.get("direction", "forward")

        # Clean label → valid C expression (best-effort)
        rate_expr = re.sub(r"[^A-Za-z0-9_./*+()^-]", "_", label)
        rate_expr = rate_expr.strip("_") or "RATE"

        if tgt != "EXTERNAL" and src != "EXTERNAL":
            lines.append(f"// {src} → {tgt}  [{label}]")
            lines.append(f"// dADT({src}) -= {rate_expr};")
            lines.append(f"// dADT({tgt}) += {rate_expr};")
            lines.append("")
        elif tgt == "EXTERNAL":
            lines.append(f"// {src} → [out]  [{label}]  (elimination)")
            lines.append(f"// dADT({src}) -= {rate_expr};")
            lines.append("")

    lines.append("// ---- Fill in numeric ODE equations below ----")
    return "\n".join(lines)


def _build_global(phys_syms: List[str], cmt_ids: List[str]) -> str:
    return "// Add allometric scaling or derived variables here"


def _build_table(cmt_ids: List[str]) -> str:
    lines = ["capture CP = 0;  // Central plasma concentration — fill in"]
    if cmt_ids:
        lines.append(f"// capture CP = {cmt_ids[1] if len(cmt_ids) > 1 else cmt_ids[0]} / VC;")
    return "\n".join(lines)


def generate_cpp(data: Dict, compound: Optional[str] = None) -> str:
    """Generate mrgsolve .cpp model string from pipeline JSON."""
    params = data.get("parameters", [])
    structure = data.get("structure")
    title = (data.get("page_metadata") or {}).get("title") or "PBPK Model"
    species = _pick_species(params)

    groups = _extract_compound_groups(params)
    compound_names = [k for k in groups if k != "Physiological"]

    # Default to first compound if not specified
    main_compound = compound or (compound_names[0] if compound_names else "Unknown")

    phys_block, phys_syms = _build_param_block(groups.get("Physiological", []))
    cmpd_block, cmpd_syms = _build_param_block(groups.get(main_compound, []))

    cmt_str, cmt_ids = _build_compartments(structure)
    ode_block = _build_ode(structure, cmt_ids)
    global_block = _build_global(phys_syms + cmpd_syms, cmt_ids)
    table_block = _build_table(cmt_ids)

    return CPP_TEMPLATE.format(
        title=title,
        species=species,
        compounds=", ".join(compound_names) or "Unknown",
        phys_params=phys_block or "// No physiological parameters extracted",
        cmpd_params=cmpd_block or "// No compound-specific parameters extracted",
        main_compound=main_compound,
        compartments=cmt_str,
        global_block=global_block,
        ode_block=ode_block,
        table_block=table_block,
    )


# ---------------------------------------------------------------------------
# R simulation script generator
# ---------------------------------------------------------------------------

R_TEMPLATE = """\
# ============================================================
#  mrgsolve simulation script
#  Generated by r_codegen.py
# ============================================================

library(mrgsolve)
library(ggplot2)
library(dplyr)

# ----- 1. Load model -----
mod <- mread("{model_name}", "{cpp_dir}")

# ----- 2. Inspect model -----
see(mod)
param(mod)

# ----- 3. Define dosing events -----
# TODO: adjust dose, interval, and number of doses to match paper
ev <- ev(
  amt   = {dose},       # dose amount (same unit as model)
  ii    = {interval},   # dosing interval (hours)
  addl  = {addl},       # additional doses
  cmt   = 1             # dosing compartment index
)

# ----- 4. Simulate -----
out <- mod %>%
  ev(ev) %>%
  mrgsim(end = {sim_end}, delta = {delta})

# ----- 5. Save results -----
out_df <- as.data.frame(out)
write.csv(out_df, "{csv_out}", row.names = FALSE)
cat("Results saved to: {csv_out}\\n")

# ----- 6. Plot -----
p <- ggplot(out_df, aes(x = time, y = CP)) +
  geom_line(color = "#2E86AB", linewidth = 1) +
  labs(
    title = "{model_name}",
    subtitle = "Simulated plasma concentration",
    x = "Time (hours)",
    y = "Concentration"
  ) +
  theme_bw()

ggsave("{plot_out}", p, width = 8, height = 5, dpi = 150)
cat("Plot saved to: {plot_out}\\n")
"""


def generate_r_script(
    model_name: str,
    cpp_dir: str,
    csv_out: str,
    plot_out: str,
    dose: float = 1.0,
    interval: float = 24.0,
    addl: int = 0,
    sim_end: float = 168.0,
    delta: float = 1.0,
) -> str:
    return R_TEMPLATE.format(
        model_name=model_name,
        cpp_dir=cpp_dir,
        csv_out=csv_out,
        plot_out=plot_out,
        dose=dose,
        interval=interval,
        addl=addl,
        sim_end=sim_end,
        delta=delta,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate mrgsolve R simulation code from a pk_pipeline JSON output."
    )
    parser.add_argument("json_path", help="Path to the pk_pipeline JSON output file")
    parser.add_argument(
        "--compound",
        default=None,
        help="Compound to model (defaults to first compound found in JSON)"
    )
    parser.add_argument(
        "--output-dir",
        default="r_output",
        help="Directory to write generated files (default: r_output/)"
    )
    parser.add_argument(
        "--dose", type=float, default=1.0,
        help="Dose amount for simulation (default: 1.0, adjust to match paper units)"
    )
    parser.add_argument(
        "--interval", type=float, default=24.0,
        help="Dosing interval in hours (default: 24)"
    )
    parser.add_argument(
        "--addl", type=int, default=0,
        help="Additional doses after first (default: 0)"
    )
    parser.add_argument(
        "--sim-end", type=float, default=168.0,
        help="Simulation end time in hours (default: 168 = 7 days)"
    )
    parser.add_argument(
        "--run", action="store_true",
        help="Execute the generated R script via Rscript after generating it"
    )
    args = parser.parse_args()

    # --- Load JSON ---
    if not os.path.exists(args.json_path):
        print(f"Error: JSON file not found: {args.json_path}", file=sys.stderr)
        sys.exit(1)

    with open(args.json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    os.makedirs(args.output_dir, exist_ok=True)

    # --- Derive model name ---
    stem = os.path.splitext(os.path.basename(args.json_path))[0]
    model_name = re.sub(r"[^A-Za-z0-9_]", "_", stem)[:40]

    # --- Generate .cpp ---
    cpp_content = generate_cpp(data, compound=args.compound)
    cpp_path = os.path.join(args.output_dir, f"{model_name}.cpp")
    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write(cpp_content)
    print(f"✓ mrgsolve model written: {cpp_path}")

    # --- Generate R script ---
    csv_out = os.path.join(os.path.abspath(args.output_dir), f"{model_name}_sim.csv")
    plot_out = os.path.join(os.path.abspath(args.output_dir), f"{model_name}_sim.png")
    cpp_dir = os.path.abspath(args.output_dir)

    r_content = generate_r_script(
        model_name=model_name,
        cpp_dir=cpp_dir,
        csv_out=csv_out,
        plot_out=plot_out,
        dose=args.dose,
        interval=args.interval,
        addl=args.addl,
        sim_end=args.sim_end,
    )
    r_path = os.path.join(args.output_dir, f"{model_name}_sim.R")
    with open(r_path, "w", encoding="utf-8") as f:
        f.write(r_content)
    print(f"✓ R simulation script written: {r_path}")

    print()
    print("Next steps:")
    print(f"  1. Review and complete the ODE equations in: {cpp_path}")
    print(f"  2. Adjust dose/interval in: {r_path}")
    print(f"  3. Run: Rscript {r_path}")
    print()

    # --- Optionally run R ---
    if args.run:
        rscript = subprocess.run(["which", "Rscript"], capture_output=True, text=True)
        if rscript.returncode != 0:
            print("⚠️  Rscript not found on PATH. Install R and mrgsolve first.")
            sys.exit(1)
        print(f"Running: Rscript {r_path}")
        result = subprocess.run(["Rscript", r_path])
        sys.exit(result.returncode)


if __name__ == "__main__":
    main()
